export const ServicesTitle: any = {
  moebelmontage: [
  "Möbelmontage (Schränke, Regale, Betten usw.)",
  "Kücheninstallation (Küchenmöbel, Elektrogeräte usw.)",
  "Montage von Schränken und Aufbewahrungssystemen",
  "Anbringung von Bildern, Spiegeln und Wanddekorationen",
  "Installation von Lampen und Beleuchtungszubehör",
  "Anbringung von Vorhängen, Jalousien und Sonnenschutzsystemen",
  "Hausreparaturen (z. B. beschädigte Türen, Schränke)",
  "Montage von TV-Halterungen und Unterhaltungselektronik",
  "Allgemeine Wartungsarbeiten (Bohren, Verankerung, kleinere Reparaturen)",
  "Beratung und Unterstützung bei Renovierungsprojekten",
  ],
  Empresas_de_aire_acondicionado: [
  "Installation von Klimaanlagensystemen (Split, Multisplit, Zentralsysteme)",
  "Wartung und Service von Klimaanlagensystemen",
  "Reparatur von Klimaanlagensystemen",
  "Klimaanlagen für Wohn- und Büroräume",
  "Klimaanlagen für gewerbliche oder industrielle Bereiche",
  "Klimaanlagen für Serverräume",
  "Installation von Belüftungssystemen",
  "Wartung und Service von Belüftungssystemen",
  "Luftreinigungssysteme und Filterwechsel",
  "Beratung zur Energieeffizienz und Optimierung von Klimasystemen",
  "Beratung zur Auswahl und Planung von Klimatisierungslösungen",
  ],
  klimatechniker: [
  "Installation von Klimaanlagensystemen (Split, Multisplit, Zentral)",
  "Wartung und Service von Klimaanlagensystemen",
  "Reparatur von Klimaanlagensystemen",
  "Klimaanlagen für Wohn- und Büroräume",
  "Klimaanlagen für gewerbliche oder industrielle Bereiche",
  "Klimaanlagen für Serverräume",
  "Installation von Belüftungssystemen",
  "Wartung und Service von Belüftungssystemen",
  "Luftreinigungssysteme und Filterwechsel",
  "Beratung zur Energieeffizienz und Optimierung von Klimasystemen",
  "Beratung zur Auswahl und Planung von Klimatisierungslösungen",
  ],
  maurer: [
    "Mauerwerksbau (Haus, Gebäude, Mauern)",
    "Mauerwerkssanierung und Reparatur",
    "Pflasterarbeiten (Wege, Einfahrten)",
    "Fundamentbau und Kellermauern",
    "Betonarbeiten (Schalung, Beton gießen)",
    "Nivellier- und Bodenausgleichsarbeiten",
    "Installation von Innen- und Trennwänden",
    "Verputzarbeiten innen und außen",
    "Fassadenarbeiten und Gestaltung",
    "Abdichtungen gegen Feuchtigkeit",
    "Beratung zu Bauprojekten und Materialien",
  ],
  Albaniles_constructores: [
    "Mauerwerksbau (Haus, Gebäude, Mauern)",
    "Mauerwerkssanierung und Reparatur",
    "Pflasterarbeiten (Wege, Einfahrten)",
    "Fundamentbau und Kellermauern",
    "Betonarbeiten (Schalung, Beton gießen)",
    "Nivellier- und Bodenausgleichsarbeiten",
    "Installation von Innen- und Trennwänden",
    "Verputzarbeiten innen und außen",
    "Fassadenarbeiten und Gestaltung",
    "Abdichtungen gegen Feuchtigkeit",
    "Beratung zu Bauprojekten und Materialien",
  ],
  gebaeudereiniger: [
  "Reinigung von Büros und Geschäften",
  "Treppenhausreinigung",
  "Fensterreinigung",
  "Reinigung von Teppichen und Polstern",
  "Bauendreinigung",
  "Grundreinigung und Bodenaufbereitung",
  "Fassadenreinigung",
  "Industriereinigung",
  "Reinigung von Glas und Spiegeln",
  "Hygiene- und Desinfektionsmaßnahmen",
  "Schädlingsbekämpfung",
  "Spezialreinigung (z. B. nach Veranstaltungen)",
  ],
  innenarchitekt: [
  "Raumplanung und Raumkonzepte",
  "Farb- und Materialkonzepte",
  "Möbelplanung und Einrichtungsberatung",
  "Beleuchtungskonzepte und Lichtplanung",
  "Küchen- und Badplanung",
  "Planung von Wohn- und Schlafräumen",
  "Gestaltung von Büro- und Gewerberäumen",
  "Umbau- und Renovierungsplanung",
  "3D-Visualisierung und Entwurfszeichnungen",
  "Beratung zu Stil, Dekoration und Accessoires",
  ],
  architekt: [
  "Planung und Gestaltung von Bauprojekten",
  "Beratung im Bauwesen und Projektmanagement",
  "Baugenehmigungen und behördliche Zulassungen",
  "Beratung zur Energieeffizienz",
  "Architektonische Planung und Raumgestaltung",
  "Kostenplanung und Bau-Budgetierung",
  "Bauüberwachung und Projektleitung",
  "Baustellenüberwachung und Qualitätskontrolle",
  "Beratung zu Nachhaltigkeit und Umweltschutz",
  ],
  schreiner: [
    "Maßgefertigte Möbelherstellung (Schränke, Regale, Tische)",
  "Montage von Küchenmöbeln und Schränken",
  "Herstellung und Montage von Treppen und Geländern",
  "Anfertigung von maßgeschneiderten Schränken und Ankleidezimmern",
  "Restauration von antiken Möbeln",
  "Reparatur und Pflege von Holzmöbeln",
  "Herstellung und Einbau von Fenstern und Türen",
  "Bau von individuellen Holzstrukturen",
  "Beratung zur Holzauswahl und Oberflächenbehandlung",
  ],
  kaminbauer: [
  "Planung und Beratung für Kamine",
  "Installation von Holzöfen und Kaminen",
  "Renovierung und Reparatur von Kaminen",
  "Arbeiten an Kaminabdeckungen und -hauben",
  "Verkleidungen und Materialien für Kamine",
  "Kaminabdeckungen und Rauchrohre",
  "Renovierung und Reinigung von Kaminen",
  "Brandschutzsysteme für Kamine",
  "Wartung und Inspektion von Kaminsystemen",
  "Beratung zur Auswahl von Kaminen und Zubehör",
  ],
  betonbohrungen: [
  "Betonbohrungen für Installationen (z. B. Rohrleitungen, Kabel)",
  "Kernbohrungen für Durchbrüche und Öffnungen",
  "Betonschnitte für Trennwände, Decken und Böden",
  "Schnitt von Dehnungs- und Fugenbereichen",
  "Fräsen von Beton zur Glättung und Oberflächenvorbereitung",
  "Sägen für Abriss und Entfernung von Beton",
  "Entfernung und Demontage von Beton",
  "Reparatur und Sanierung von Betonrissen",
  "Spezialdienste (z. B. Betonverdichtung, Temperaturmessung)",
  ],
  tecnico_climatico: [
  "Installation einer neuen Heizungsanlage",
  "Reparatur oder Wartung einer bestehenden Heizungsanlage",
  "Installation einer Klimaanlage oder HVAC-Anlage",
  "Reparatur oder Wartung einer Klimaanlage oder HVAC-Anlage",
  "Installation oder Wartung von Lüftungssystemen",
  "Installation oder Reparatur von Wärmepumpen",
  "Installation oder Fehlerbehebung bei Thermostaten",
  "Austausch von Luftfiltern oder Verbesserung der Raumluftqualität",
  "Beratung zu Energieeffizienz und Systemoptimierung",
  ],
  Técnicas_climáticas: [
  "Installation einer neuen Heizungsanlage",
  "Reparatur oder Wartung einer bestehenden Heizungsanlage",
  "Installation einer Klimaanlage oder HVAC-Anlage",
  "Reparatur oder Wartung einer Klimaanlage oder HVAC-Anlage",
  "Installation oder Wartung von Lüftungssystemen",
  "Installation oder Reparatur von Wärmepumpen",
  "Installation oder Fehlerbehebung bei Thermostaten",
  "Austausch von Luftfiltern oder Verbesserung der Raumluftqualität",
  "Beratung zu Energieeffizienz und Systemoptimierung",
  ],
  talleres_de_automoviles: [
  "Inspektion und Wartung",
  "Motor- und Antriebsstrangreparatur",
  "Bremsen- und Fahrwerksservice",
  "Diagnose und Fehlerbehebung",
  "Ölwechsel und Filterwechsel",
  "Reifenwechsel und -service",
  "Klimaanlagenservice und -wartung",
  "Karosserie- und Lackierarbeiten",
  "Reparatur und Austausch von Windschutzscheiben",
  "Elektrische und elektronische Reparaturen",
  "Fahrzeuginspektion (TÜV) und Abgastests",
  "Beratung beim Fahrzeugkauf und Auswahl",
  ],
  autowerkstatt: [
  "Inspektion und Wartung",
  "Motor- und Antriebsstrangreparatur",
  "Bremsen- und Fahrwerksservice",
  "Diagnose und Fehlerbehebung",
  "Ölwechsel und Filterwechsel",
  "Reifenwechsel und -service",
  "Klimaanlagenservice und -wartung",
  "Karosserie- und Lackierarbeiten",
  "Reparatur und Austausch von Windschutzscheiben",
  "Elektrische und elektronische Reparaturen",
  "Fahrzeuginspektion (TÜV) und Abgastests",
  "Beratung beim Fahrzeugkauf und Auswahl",
  ],
  trockenbauer: [
  "Installation von Wänden und Decken aus Gipskartonplatten",
  "Montage von Raumteilern und Trennwänden",
  "Installation von Dämmungen (thermisch, akustisch oder Brandschutz)",
  "Verkleidung von Rohrleitungen und Installationen",
  "Installation von Gipsplattensystemen (z. B. Verkleidungen)",
  "Bau von Gipskarton- und Leichtbaukonstruktionen",
  "Trockenbauarbeiten für Innenausbauten (z. B. Einbauschränke)",
  "Brandschutzmaßnahmen und feuerfeste Verkleidungen",
  "Reparatur und Renovierung von Gipskartonstrukturen",
  "Beratung zur Material- und Technikauswahl im Trockenbau",
  ],
  demolicion_y_eliminacion: [
  "Komplettrückbau von Gebäuden und Strukturen",
  "Teilweise Demontage/Rückbau von Gebäuden",
  "Asbestentfernung",
  "Entsorgung und Recycling von Baumaterialien",
  "Entsorgung von gefährlichen Abfällen",
  "Container und Abfallbeseitigung",
  "Reinigung von Baustellen",
  ],
  abbruchunternehmen: [
  "Komplettrückbau von Gebäuden und Strukturen",
  "Teilweise Demontage/Rückbau von Gebäuden",
  "Asbestentfernung",
  "Entsorgung und Recycling von Baumaterialien",
  "Entsorgung von gefährlichen Abfällen",
  "Container und Abfallbeseitigung",
  "Reinigung von Baustellen",
  ],
  elektriker: [
  "Elektroinstallationen für Neubauten",
  "Elektrische Inspektion und Zertifizierung",
  "Elektroinstallationen bei Renovierungen und Umbauten",
  "Elektrische Reparaturen und Wartung",
  "Installation und Aufrüstung von Sicherungskästen",
  "Beleuchtungsinstallation (innen und außen)",
  "Installation von Steckdosen und Schaltern",
  "Installation von Netzwerken und Datenkabeln",
  "Videoüberwachungssysteme",
  "Installation von Alarmsystemen",
  "Smart-Home-Integration",
  "Fehlerdiagnose und Behebung elektrischer Probleme",
  "Beratung und Planung von Elektroprojekten",
  ],
  erdarbeiten: [
  "Aushub- und Erdarbeiten",
  "Nivellierung von Baustellen",
  "Auffüllung und Verdichtung von Grundstücken",
  "Graben- und Aushubarbeiten für Fundamente und Rohrleitungen",
  "Bohrloch- und Schachtarbeiten",
  "Abfallbeseitigung und Schuttmanagement",
  "Beratung zur Auswahl von Geräten und Aushubtechniken",
  "Bau von Straßen und Zufahrten",
  "Landschaftsbauarbeiten",
  "Geländemodellierung und Wiederherstellung von Flächen",
  ],
  zaunbauer: [
  "Zaunbau (Holz, Metall, Kunststoff, etc.)",
  "Installation von Garten- und Grundstückszäunen",
  "Installation von Sichtschutzwänden und Zäunen",
  "Reparatur und Wartung von Zäunen",
  "Einbau von Türen und Eingangstoren",
  "Bau von Gabionen und Lärmschutzwänden",
  "Beratung zur Material- und Designauswahl von Zäunen",
  "Maßgeschneiderte Zaunlösungen",
  "Pflanzung von Kletterpflanzen und Begrünung",
  ],
  bodenleger: [
  "Verlegung von Bodenbelägen (z. B. Hartholz, Laminat, Fliesen)",
  "Estricharbeiten (z. B. Vorbereitung des Untergrunds, Einbau von Estrich)",
  "Industrielle Bodenbeschichtungen",
  "Bodenrenovierung und -reparaturen",
  "Terrassen- und Balkonbeläge",
  "Installation und Integration von Fußbodenheizung",
  "Treppenbeläge und Renovierung",
  "Barrierefreie Bodenlösungen",
  "Schall- und Trittschalldämmung",
  "Beratung zur Auswahl geeigneter Bodenmaterialien",
  ],
  glaserei: [
  "Einbau von Fenstern und Türen",
  "Glasreparatur und Schadensbehebung",
  "Glaszuschnitt und individuelle Anpassungen",
  "Einbau und Herstellung von Spiegeln",
  "Glastrennwände und Raumteiler",
  "Glasduschen und Duschkabinen",
  "Glastische und Glasplatten",
  "Sicherheits- und Einbruchschutzlösungen für Glas",
  "Schaufenster und Vitrinen",
  "Wintergartenbau",
  "Beratung zu Glasarten und -lösungen",
  ],
  instaladoras_de_calefaccion: [
  "Installation von Heizsystemen (Gas, Öl oder Fernwärme)",
  "Installation von Fußbodenheizungen",
  "Einbau von Heizkörpern und Austausch von Heizkörpern",
  "Wartung und Reparatur von Heizsystemen",
  "Beratung zur Optimierung und Energieeffizienz",
  "Installation von Thermostaten und Steuerungssystemen",
  "Brennwerttechnik und Integration von Solarsystemen",
  "Belüftung und Verlegung von Heizungsrohren",
  "Notfallreparaturen bei Heizungsstörungen",
  "Beratung zur Auswahl von Heizsystemen",
  ],
  heizungsbauer: [
  "Installation von Heizsystemen (Gas, Öl oder Fernwärme)",
  "Installation von Fußbodenheizungen",
  "Einbau von Heizkörpern und Austausch von Heizkörpern",
  "Wartung und Reparatur von Heizsystemen",
  "Beratung zur Optimierung und Energieeffizienz",
  "Installation von Thermostaten und Steuerungssystemen",
  "Brennwerttechnik und Integration von Solarsystemen",
  "Belüftung und Verlegung von Heizungsrohren",
  "Notfallreparaturen bei Heizungsstörungen",
  "Beratung zur Auswahl von Heizsystemen",
  ],
  raumausstatter: [
  "Bodenbeläge (Teppich, Laminat, Parkett, Fliesen, etc.)",
  "Wanddekoration (Tapeten, Anstrich, Wandverkleidungen)",
  "Fensterbehandlungen (Vorhänge, Gardinen, Jalousien, Rollos)",
  "Sonnenschutz (Markisen, Plissees, Jalousien)",
  "Polsterarbeiten (Möbelrestaurierung, Polsterreparaturen)",
  "Innenplanung und -gestaltung",
  "Akustiklösungen (Schallschutz, Raumakustik)",
  "Raumaufteilung und Platzplanung",
  "Maßgefertigte Möbel und Einrichtungsgegenstände",
  "Beratung zur Materialauswahl und Gestaltung",
  ],
  kuechenbauer: [
  "Komplette Kücheninstallation (einschließlich Schränke, Arbeitsplatten, Geräte, etc.)",
  "Installation oder Austausch von Küchenschränken",
  "Installation oder Austausch von Arbeitsplatten",
  "Installation von Küchengeräten",
  "Anbringung von Spritzschutz",
  "Installation oder Austausch von Fußböden",
  "Installation einer Kücheninsel",
  "Maßgeschneiderte Küchenmöbelarbeiten",
  ],
  gartenbauer: [
  "Planung und Gestaltung des Gartens",
  "Installation und Pflege von Rasenflächen",
  "Pflanzung und Pflege von Bäumen",
  "Anlage von Teichen und Wassergärten",
  "Bau von Terrassen und Wegen",
  "Mauern und Steinarbeiten",
  "Gartenbeleuchtung und Außenaccessoires",
  "Sichtschutz und Zauninstallationen",
  "Gartenbewässerungssysteme",
  "Installation von Dachbegrünung und Gründächern",
  "Gartenpflege und Instandhaltung",
  "Beratung zur Auswahl von Pflanzen und Gartengestaltungslösungen",
  ],
  umzugsunternehmen: [
  "Umzugsplanung und -organisation",
  "Bereitstellung von Umzugsmaterialien (Kisten, Verpackungsmaterialien)",
  "Verpackungsservice (Verpacken von Gegenständen und Möbeln)",
  "Abbau und Aufbau von Möbeln",
  "Transport von Möbeln und persönlichen Gegenständen",
  "Be- und Entladen von Gegenständen",
  "Aufbau von Möbeln und Abbau am neuen Standort",
  "Endreinigung der alten Wohnung oder Räumlichkeiten",
  "Lagerung von Möbeln oder persönlichen Gegenständen",
  "Umzugshilfe für Senioren oder Personen mit eingeschränkter Mobilität",
  ],
  metallbauer: [
  "Herstellung und Montage von Metallstrukturen",
  "Metallarbeiten für Treppen, Geländer und Balkone",
  "Schweißen und Metallreparaturen",
  "Herstellung und Montage von Metallzäunen und -toren",
  "Herstellung von Metallfassaden und -verkleidungen",
  "Metallfertigung (Schneiden, Biegen, Schweißen)",
  "Individuelle Herstellung und Montage von Stahlkonstruktionen",
  "Produktion von maßgefertigten Metallkomponenten",
  "Montage von Metallfenstern und -türen",
  "Beratung zur Auswahl von Metallmaterialien und -designs",
  ],
  stuckateur: [
  "Innenverputz (glatt, strukturiert, Kalkputz usw.)",
  "Außenverputz (Grundputz, Fassadenputz)",
  "Wärmedämmputz (isolierender Putz)",
  "Renovierungsputz (bei Feuchtigkeitsschäden oder Schimmelbefall)",
  "Reparatur von Putzschäden (Risse, Absplitterungen)",
  "Glätten und Nivellieren von Wänden und Decken",
  "Verputzen von Trennwänden aus Gipskartonplatten",
  "Putzbeschichtungen und -oberflächen",
  "Beratung zur Auswahl von Putzarten und -techniken",
  ],
  pflasterer: [
  "Verlegung von Pflastersteinen und Gehwegplatten",
  "Bau von Einfahrten, Parkplätzen und Hofoberflächen",
  "Gestaltung von Terrassen und Außenbereichen",
  "Bau von Natursteinmauern und Gabionen",
  "Asphaltarbeiten (Reparaturen, Neubau von Straßen)",
  "Bau von Wegen und Radwegen",
  "Bau von Entwässerungssystemen und Kanälen",
  "Herstellung von Betonflächen (Gehwege, Plätze)",
  "Beratung zur Auswahl von Materialien und Designs",
  "Renovierung und Instandhaltung von Pflasterflächen und Straßenbelägen",
  ],
  poolbauer: [
  "Beratung und Planung für den Poolbau",
  "Bau von neuen Pools",
  "Installation von Fertigpools oder maßgefertigten Pools",
  "Installation von Poolausrüstung (Filtersystem, Pumpe, Heizung)",
  "Verlegung von Poolfliesen oder Poolbeschichtungen",
  "Bau von Poolabdeckungen und Poolumgebungen",
  "Gestaltung der Poollandschaft und Poolbeleuchtung",
  "Wartung und Reinigung des Pools",
  "Reparatur und Renovierung bestehender Pools",
  "Beratung zur Auswahl von Poolzubehör und -ausrüstung",
  ],
  maler: [
  "Innenanstrich von Wänden und Decken",
  "Außenanstrich von Fassaden",
  "Anstrich von Türen, Fenstern und Holzoberflächen",
  "Tapeten und Wandverkleidungen",
  "Spachtel- und Putzarbeiten",
  "Schimmelentfernung und Feuchtigkeitssanierung",
  "Farbberatung und Farbkonzepte",
  "Dekorative Maltechniken (z. B. Lasur, Stuck)",
  "Anstrich von Metalloberflächen (z. B. Geländer, Treppen)",
  "Bodenbeschichtungen und industrielle Anstriche",
  "Reinigung und Schutz der Fassade",
  "Beratung zur Auswahl von Farben und Materialien",
  ],
  sanitaer: [
  "Installation von Sanitärarmaturen (Waschbecken, WC, Dusche, Badewanne)",
  "Reparatur von Rohrleitungen und Wasseranschlüssen",
  "Austausch oder Installation von Wasserhähnen und Armaturen",
  "Installation von Wassererhitzern und Heizkesseln",
  "Installation und Wartung von Heizungssystemen",
  "Installation und Reparatur von Abwasser- und Kanalisationssystemen",
  "Renovierung von Bädern und sanitären Anlagen",
  "Installation von Wasseraufbereitungssystemen (z. B. Wasserenthärter)",
  "Barrierefreie Anpassungen für Bäder (z. B. bodengleiche Duschen)",
  "Beratung zur Auswahl von Sanitärprodukten und Installationen",
  ],
  dachdecker: [
  "Installation und Austausch des Daches",
  "Reparatur und Wartung des Daches",
  "Restaurierung und Renovierung des Daches",
  "Installation und Reparatur von Dachrinnen",
  "Dachisolierung und -dämmung",
  "Installation und Austausch von Dachfenstern (Skylights)",
  "Verkleidung und Reparatur von Fassaden",
  "Abdichtung und Reparatur des Kamins",
  "Beschichtung und Reinigung des Daches",
  "Reparaturen von Sturmschäden",
  ],
  geruestbauer: [
  "Gerüste für Bau- und Renovierungsprojekte",
  "Fassadengerüste",
  "Gerüste für Projekte im Bereich Ingenieurbau und Hochbau",
  "Eventgerüste",
  "Spezialisierte Gerüste (z. B. für Brücken, Türme)",
  "Witterungsschutz und Schutzräume",
  "Gerüstvermietung",
  "Abbau und Entfernung von Gerüsten",
  "Gerüsteinspizierung und Sicherheitskontrollen",
  "Wartung und Reparaturen von Gerüsten",
  "Beratung zur Planung von Gerüsten",
  ],
  treppenbauer: [
  "Planung und Design von maßgeschneiderten Treppenlösungen",
  "Bau neuer Treppen (Holz, Metall, Beton, etc.)",
  "Renovierung und Modernisierung bestehender Treppen",
  "Installation von Treppengeländern und Handläufen",
  "Trittstufen und Treppenbeläge (Holz, Stein, Fliesen, etc.)",
  "Maßgefertigte Treppenbauten",
  "Umgestaltung und Erweiterung von Treppen",
  "Beratung zur Auswahl von Materialien und Treppendesigns",
  ],
  polsterer: [
  "Polsterarbeiten (Restaurierung von Möbeln, Stühlen)",
  "Reparatur und Restaurierung von Polstermöbeln",
  "Herstellung von maßgeschneiderten Polstermöbeln",
  "Produktion von Kissen und Rückenlehnen",
  "Herstellung von Polsterbezügen für Autositzpolster",
  "Polsterarbeiten für Boote und Yachten",
  "Sattlerarbeiten (Restaurierung von Autositzen, Motorradsitzen)",
  "Herstellung von maßgefertigten Lederwaren und Zubehör",
  "Restaurierung von antiken Möbeln und Lederwaren",
  "Beratung zur Auswahl von Stoffen und Lederarten",
  ],
  fliesenleger: [
  "Verlegung von Fliesen für Böden",
  "Verlegung von Mosaiken für Wände",
  "Verlegung von Fliesen für Küchen und Badezimmer",
  "Bodenbeläge für Terrassen und Balkone",
  "Verlegung von Naturstein",
  "Dekorative Mosaike und Fliesen",
  "Fliesenschneiden und Zubehör",
  "Versiegelung und Abdichtung von Fugen",
  "Renovierung und Reparatur von Fliesen",
  "Barrierefreie Lösungen für Böden und Duschen",
  "Beratung zur Auswahl von Mosaiken und Designs",
  ],
  Empresas_de_transporte: [
  "Umzugsdienste (privater oder gewerblicher Umzug)",
  "Transport und Montage von Möbeln",
  "Lokale und regionale Lieferungen und Transporte",
  "Ferntransport (national oder international)",
  "Expresslieferung und Kurierdienste",
  "Transport von voluminösen oder schweren Gütern",
  "Lagerungs- und Aufbewahrungsdienste",
  "Entsorgungsdienste (Abfallentsorgung, Schrottentsorgung)",
  "Spezialtransporte (z. B. Transport von gefährlichen Materialien)",
  "Beratung und Planung von Transportlösungen",
  ],
  brunnenbauer: [
  "Bohrung von Trinkwasserbrunnen",
  "Brunnen für landwirtschaftliche Zwecke",
  "Brunnen für Bewässerungssysteme",
  "Brunnen für geothermische Heizungs- und Kühlsysteme",
  "Brunnen für industrielle Zwecke",
  "Wartung und Reparatur von Brunnen",
  "Auswahl und Installation von Pumpen",
  "Wasserqualitätsprüfungen und -analysen",
  "Beratung zur Auswahl und Planung von Brunnen",
  ],
  fensterbauer: [
  "Herstellung und Installation von Fenstern",
  "Herstellung und Installation von Türen",
  "Herstellung und Installation von Markisen",
  "Installation und Reparatur von Rolladenverschlüssen",
  "Bau von Wintergärten und Verglasungen",
  "Glasarbeiten und Verglasung",
  "Installation von Insektenschutzgittern",
  "Einbruchschutzlösungen",
  "Barrierefreie Lösungen für Fenster und Türen",
  "Sonnenschutzlösungen (z. B. Jalousien, Plissee-Jalousien)",
  "Reparatur und Wartung von Fenstern und Türen",
  "Beratung zur Auswahl von Fenstern, Türen und Markisen",
  ],
  Construcción_de_ventanas: [
  "Herstellung und Installation von Fenstern",
  "Herstellung und Installation von Türen",
  "Herstellung und Installation von Markisen",
  "Installation und Reparatur von Rollladenverschlüssen",
  "Bau von Wintergärten und Verglasungen",
  "Glasarbeiten und Verglasung",
  "Installation von Insektenschutzgittern",
  "Einbruchschutzlösungen",
  "Barrierefreie Lösungen für Fenster und Türen",
  "Sonnenschutzlösungen (z. B. Jalousien, Plissee-Jalousien)",
  "Reparatur und Wartung von Fenstern und Türen",
  "Beratung zur Auswahl von Fenstern, Türen und Markisen",
  ],
  Preservación_de_la_madera: [
  "Holzschutz und Holzimpregnierung",
  "Schutz von Gebäuden vor Feuchtigkeit und Schimmel",
  "Schädlingsbekämpfung im Holz- und Bauwesen",
  "Versiegelung und strukturelle Beschichtung",
  "Feuchtigkeitsmanagement im Keller und Feuchtigkeitsbeseitigung",
  "Impregnierung und Schutz der Fassade",
  "Balkon- und Terrassenbeschichtung",
  "Restaurierung und Reparatur von Holz",
  "Renovierung und Schutz der Dachkonstruktion",
  "Beratung zur Schadensprävention",
  ],
  holzschutz: [
  "Holzschutz und Holzimpregnierung",
  "Schutz von Gebäuden vor Feuchtigkeit und Schimmel",
  "Schädlingsbekämpfung im Holz- und Bauwesen",
  "Versiegelung und strukturelle Beschichtung",
  "Feuchtigkeitsmanagement im Keller und Feuchtigkeitsbeseitigung",
  "Impregnierung und Schutz der Fassade",
  "Balkon- und Terrassenbeschichtung",
  "Restaurierung und Reparatur von Holz",
  "Renovierung und Schutz der Dachkonstruktion",
  "Beratung zur Schadensprävention",
  ],
};
